from dataclasses import dataclass

@dataclass
class Chunk():
    chunk_text: str
    embedding: list[float]  # vector, generated by embedding model
    chunk_number: int

@dataclass
class FileChunkBundle():
    dir_path: str
    filename: str
    chunks: list[Chunk]
    filesize: int
    metadata: dict  # misc metadata