from dataclasses import dataclass

@dataclass
class File():
    dir_path: str
    filename: str
    chunk_count: int
    filesize: int
    metadata: dict  # misc metadata

@dataclass
class Chunk():
    chunk_text: str
    embedding: list[float]  # vector, generated by embedding model
    chunk_number: int
    file: File