from dataclasses import dataclass

@dataclass
class Chunk():
    chunk_text: str
    embedding: list[float]  # vector, generated by embedding model
    chunk_number: int

@dataclass
class FileBundle():
    dir_path: str
    filename: str
    chunks: list[str]
    filesize: int
    metadata: dict  # misc metadata

    @property
    def total_chunks(self):
        return len(self.chunks)