-- Reminding myself of how to SQL 🥲
SELECT * FROM chunk;

-- get the maximum project_id in the table
SELECT max(project_id) FROM chunk

-- subquery
SELECT project_id, filename FROM chunk WHERE project_id=(SELECT max(project_id) FROM chunk);

-- embedding is generated by OpenAI embedding model
INSERT INTO chunk (project_id, filename, dir_path, chunk_text, embedding, chunk_number, total_chunks, filesize, metadata)
VALUES (2, 'lorem', '/home/bob/obsidian', 'the quick brown fox', '[1,2,...,3]', 1, 1, 42, '{}')


-- CREATE TABLE IF NOT EXISTS chunk (
--     id IDENTITY PRIMARY KEY,
--     project_id BIGINT NOT NULL,
--     filename VARCHAR(500) NOT NULL,
--     dir_path VARCHAR(500) NOT NULL,
--     chunk_text TEXT NOT NULL,
--     embedding VECTOR({env['VECTOR_DIMS']}) NOT NULL,
--     chunk_number INTEGER NOT NULL,
--     total_chunks INTEGER NOT NULL,
--     filesize INTEGER NOT NULL,
--     metadata JSONB NOT NULL