from dataclasses import dataclass
from typing import TypedDict                                                            

@dataclass
class Chunk():
    chunk_text: str
    embedding: list[float]  # vector, generated by embedding model
    chunk_number: int

    # Denormalized data from FileBundle:
    total_chunks: int
    dir_path: str
    filename: str
    filesize: int
    metadata: dict 

@dataclass
class FileBundle():
    dir_path: str
    filename: str
    chunks: list[str]
    filesize: int
    metadata: dict  # misc metadata

    @property
    def total_chunks(self):
        return len(self.chunks)
    
                                                                                        
class SimilarChunk(TypedDict):                                                          
    id: int                                           
    project_id: int
    filename: str
    dir_path: str
    chunk_text: str
    cosine_similarity: float   